#!/usr/bin/env python3

print('::set-output name=matrix::' + str([
{
  'board': 'UPDuino-v3.0',
  'design': 'MinimalBoot',
  'bitstream': 'neorv32_UPDuino-v3.0_MinimalBoot.bit'
}, {
  'board': 'UPDuino-v3.0',
  'design': 'UP5KDemo',
  'bitstream': 'neorv32_UPDuino-v3.0_UP5KDemo.bit'
}, {
  'board': 'Fomu',
  'design': 'Minimal',
  'bitstream': 'neorv32_Fomu_pvt_Minimal.bit'
}, {
  'board': 'Fomu',
  'design': 'MinimalBoot',
  'bitstream': 'neorv32_Fomu_pvt_MinimalBoot.bit'
}, {
  'board': 'Fomu',
  'design': 'MixedLanguage',
  'bitstream': 'neorv32_Fomu_pvt_MixedLanguage.bit'
}, {
  'board': 'Fomu',
  'design': 'UP5KDemo',
  'bitstream': 'neorv32_Fomu_pvt_UP5KDemo.bit'
}, {
  'board': 'iCEBreaker',
  'design': 'MinimalBoot',
  'bitstream': 'neorv32_iCEBreaker_MinimalBoot.bit'
}, {
  'board': 'iCEBreaker',
  'design': 'UP5KDemo',
  'bitstream': 'neorv32_iCEBreaker_UP5KDemo.bit'
}, {
  'board': 'iCESugar-v1.5',
  'design': 'Minimal',
  'bitstream': 'neorv32_iCESugar-v1.5_Minimal.bit'
}, {
  'board': 'iCESugar-v1.5',
  'design': 'MinimalBoot',
  'bitstream': 'neorv32_iCESugar-v1.5_MinimalBoot.bit'
}, {
  'board': 'OrangeCrab',
  'design': 'MinimalBoot',
  'bitstream': 'neorv32_OrangeCrab_r02-25F_MinimalBoot.bit'
}, {
  'board': 'IceZumAlhambraII',
  'design': 'MinimalBoot',
  'bitstream': 'neorv32_IceZumAlhambraII_MinimalBoot.bit'
}, {
  'board': 'ULX3S',
  'design': 'MinimalBoot',
  'bitstream': 'neorv32_ULX3S_MinimalBoot.bit'
}, {
  'board': 'iCE40CW312',
  'design': 'MinimalBoot',
  'bitstream': 'neorv32_iCE40CW312_MinimalBoot.bit'
}]))
